### ISSUE TITLE
Don't do action when editing layer names

### ISSUE THREAD

**Issue by MiguelDebruyne** [bomberstudios/sketch-duplicate-and-nudge#1]
When editing the text of a layer in the layers panel / when editing text in a text layer, it's pretty normal to use alt + left/right to go to the next/prev word in line (at least in OSX). But when doing that the action 'Duplicate and nudge' is also being activated. It would be nice if this was turned off when doing these things.

As always, thanks for your time!

**Comment by bomberstudios** [comment]
Hi there. This is something that also bites me every now and then, but it's actually something we need to fix in Sketch itself (for my own reference: filed as BohemianCoding/Sketch#1269).

**Comment by MiguelDebruyne** [comment]
I see. Well then i hope they will change this in the future :)
Btw, your link does not work. _Just saying_

**Comment by bomberstudios** [comment]
Of course it doesn't work, it points to a private repo : )

**Comment by tosfan4ever** [comment]
PLEASE UNSUBSCRIBE ME TO THIS.

> On Apr 27, 2016, at 12:45 PM, Ale Muñoz <notifications@github.com> wrote:
> 
> Of course it doesn't work, it points to a private repo : )
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/bomberstudios/sketch-duplicate-and-nudge/issues/1#issuecomment-215143918>

Cheers,
````````````````````````````````````````````````````````````````
Tian-Yuan Zhao
Engineer, Entrepreneur, and Entertainer
Management/Systems Engineering - University of Toronto
Personal Website - http://www.tianyuanzhao.me <http://tianyuanzhao.me/>T: 1-647-716 -3730 | Skype: tosfan4ever
Book Me - http://bit.ly/1Cjyj6b <http://bit.ly/1Cjyj6b>
"Stay Hungry, Humble, and Hopeful!"
